name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the project
        run: uv build

      - name: Install the project and dependencies
        run: uv sync --all-extras

      - name: Lint
        uses: astral-sh/ruff-action@v3

      - name: Type checkg
        run: |
          uv tool install ty
          ty check src
          ty check tests

      - name: Run tests with coverage
        run: uv run coverage run -m pytest

      - name: Produce coverage report
        run: uv run coverage report -m
